apiVersion: apps/v1
kind: Deployment
metadata:
  name: javahelloworld
spec:
  selector:
    matchLabels:
      app: javahelloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: javahelloworld
    spec:
      containers:
      - name: javahelloworld   
        image: hyd.ocir.io/ax4qhhyy6wvq/privateregistry/java:81
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      imagePullSecrets:
      - name: ocirsecret