apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnethelloworld
spec:
  selector:
    matchLabels:
      app: dotnethelloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnethelloworld
    spec:
      containers:
      - name: dotnethelloworld   
        image: hyd.ocir.io/ax4qhhyy6wvq/privateregistry/dotnet:81
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ocirsecret