apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "javahelloworld.fullname" . }}
  labels:
    {{- include "javahelloworld.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "javahelloworld.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "javahelloworld.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}